### ISSUE TITLE
Save token properly

### ISSUE THREAD

**Issue by reyniersbram** [xerbalind/dodona.nvim#6]
The user is now asked to put his secret Dodona Token in his config. Because of this the config cannot be put in a public repository without the key leaking.
An idea to fix this could be to e.g. prompt the user for a token when the plugin is first loaded, and then store it somewhere. I think a good location to store it could be `vim.fn.stdpath("data") .. "/dodona/token"`

**Comment by xerbalind** [comment]
Yeah that's how It should be properly done, will look into this.

**Comment by xerbalind** [comment]
Added it, you can reopen this issue if something is still not right

**Comment by xerbalind** [comment]
there is also a new command `DodonaSetToken` but when it's not set, it should automatically ask for it
